### ISSUE TITLE
Unable to find a specification for `AdManager`

### ISSUE THREAD

**Issue by tringmani** [Musjoy/AdManager#1]
I am using XCode 8 Beta 6 with Swift 3.0

Cocoapod version is 1.0.1

I am trying to  install AdManager SDK using pod 'AdManager' but I am getting the following error.

Please refer the screenshot attached.

![screen shot 2016-08-23 at 3 42 16 pm](https://cloud.githubusercontent.com/assets/9689228/17892523/5fbabd04-695f-11e6-84c9-feb4c0eed1fe.png)

**Comment by Raymond-HL** [comment]
You should update the repository of cocoapods first.
`pod repo update`
